### ISSUE TITLE
proposal for privacy policy

### ISSUE THREAD

**Issue by kylemcdonald** [CreativeInquiry/terrapattern-website#1]
### What data do you collect from this site's visitors?

_The following statement constitutes our privacy policy:_ We are strongly committed to protecting the privacy and anonymity of the visitors to this site. We collect visitor data using Google Analytics, and we only share collected information in aggregate (such as most commonly clicked locations). We do not otherwise collect any visitor information, and don't track or profile you. We also collect user data from the optional [visitor feedback survey](http://goo.gl/forms/8T7zY28nHm).

**Comment by workergnome** [comment]
I'm OK with this.  @golanlevin?

**Comment by golanlevin** [comment]
Yes thanks for the correction.

**Comment by golanlevin** [comment]
Yes, good correction - thanks

**Comment by workergnome** [comment]
Integrated!
